config {
    type: "table",
    description: "Dimension table for sales territories.",
    tags: ["dimensions"]
}

-- This model creates a simple dimension table for sales territories.
-- A surrogate key is generated using FARM_FINGERPRINT on the business key (TerritoryID).

SELECT
    FARM_FINGERPRINT(CAST(territory_id AS STRING)) as territory_key,
    territory_id,
    name as territory_name,
    country_region_code,
    `group`
FROM
    `team_day_2025_adventure_works_oltp.sales_territory`
